### ISSUE TITLE
"only generation of JSON objects or arrays allowed (JSON::GeneratorError)"

### ISSUE THREAD

**Issue by venantius** [codementordev/cm-quiz#1]
Hey there!

I'm trying to test against an app running on localhost and getting the following stacktrace:

```
▸ cm-quiz test --endpoint=localhost:8080
Start test localhost:8080
please wait...
/Users/ursa/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:286:in `generate': only generation of JSON objects or arrays allowed (JSON::GeneratorError)
	from /Users/ursa/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:286:in `pretty_generate'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:46:in `block in build_message'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:31:in `map'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:31:in `build_message'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:11:in `perform'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/cli.rb:19:in `test'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/bin/cm-quiz:8:in `<top (required)>'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/cm-quiz:23:in `load'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/cm-quiz:23:in `<main>'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

I've got RVM installed and am using Ruby 2.3.0 and didn't seem to encounter any issues during the installation, so I'm not sure what's going on here. I'm not a Ruby expert but it looks like the test runner is failing to serialize the `options` variable, and a small amount of debugging on my end suggests that somehow options is set to nil at serialization time. 

I'm not sure exactly how that's happening, but it's a little frustrating to work with. My API is anything but compliant at the moment, but ideally the test runner shouldn't die with a stacktrace because the API isn't returning the right results.

**Comment by ocowchun** [comment]
Hi @venantius can you try to add specific HTTP protocol to your test command, for example:

```sh
$ cm-quiz test --endpoint=http://localhost:8080
```

**Comment by venantius** [comment]
Yep, checked that as well:

```▸ cm-quiz test --endpoint=http://localhost:8080
Start test http://localhost:8080
please wait...
/Users/ursa/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:286:in `generate': only generation of JSON objects or arrays allowed (JSON::GeneratorError)
	from /Users/ursa/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:286:in `pretty_generate'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:46:in `block in build_message'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:31:in `map'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:31:in `build_message'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:11:in `perform'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/cli.rb:19:in `test'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/bin/cm-quiz:8:in `<top (required)>'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/cm-quiz:23:in `load'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/cm-quiz:23:in `<main>'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by ocowchun** [comment]
ok , let me try to figure out the core reason🤔

**Comment by venantius** [comment]
I tossed `puts result[0]` into the `build_message` loop for failed results and that's what led me to conclude that it's the `options` being `nil` that causes the issue, but I couldn't figure out what causes options to be nil.

```▸ cm-quiz test --endpoint=http://localhost:8080
Start test http://localhost:8080
please wait...
{:verb=>:get, :path=>"/me", :options=>{:headers=>{"x-access-token"=>"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1MDY5NDA2ODksImlkIjoiY2hsY2xidTgxIiwiZW1haWwiOiJqYWNrLWJsYWNrQGNvZGVtZW50b3IuaW8iLCJuYW1lIjoiSmFjayBCbGFjayJ9.VcKruj0KDvCs__0_G1RbeTatUpUNk79mXdw7x3ukg8Sf4UTVHvUtTgXkUsnGA8gFxlGG5LSsA5qh0ZxBcZaFu59vikuOzjCJ00qFrowWAvcA_buMBJUg8sib4tBAcGm4INYSJHvpOPS7GfF2wfnpx1nc0LJOPxBUhJJxB4je7v9U4WmxJ8rVjBr2w-wuzOVFjw5G9o9Wt_t4XkS18Y3S5cHHnVOehuSer-0hvgIh2XfSq6QeBb9bPxwHr85Ks2GttXRChmn2rSrbhasnbnIwMGSbffktVnLHDk1zD3qXCJ0DNaGdgg1S89gUOWYPol0wRGXmuYrEVpGHlO0TjmopcCCB7h1tNH4q3JTxk5lfNBbN5nE0CdjIJe_sr5O50ZT7686rRfEBDZUpvmqSvOOv18Nn9QTcG5PmPe6A6bWnFtKL7E4gdA7T0GG9c5o1Jp7rsFmMaCWEkxbaNKcfR3VucPuStq4lLENWA3-60sNyHKAPYhwT2s2w4s0m3cMiK7xkEidDptpy8L49IyJ1BmHxPpLlVF371X-o9dpRM5LYjXWjDC_v1QKOkkMAzQ3jcK3mRpUWKXBKO6Ts-Bupsdbm2Cl2fTFaXTjwRZT990d2FhXXoDI-gROqb30Whf3Z2ZtHptnDf1zk6WJO1E_VlX8yH3oOMMBZch51mL0NnffPC2Y"}}}
{:verb=>:post, :path=>"/ideas", :options=>{:headers=>{"x-access-token"=>"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1MDY5NDA2ODksImlkIjoiY2hsY2xidTgxIiwiZW1haWwiOiJqYWNrLWJsYWNrQGNvZGVtZW50b3IuaW8iLCJuYW1lIjoiSmFjayBCbGFjayJ9.VcKruj0KDvCs__0_G1RbeTatUpUNk79mXdw7x3ukg8Sf4UTVHvUtTgXkUsnGA8gFxlGG5LSsA5qh0ZxBcZaFu59vikuOzjCJ00qFrowWAvcA_buMBJUg8sib4tBAcGm4INYSJHvpOPS7GfF2wfnpx1nc0LJOPxBUhJJxB4je7v9U4WmxJ8rVjBr2w-wuzOVFjw5G9o9Wt_t4XkS18Y3S5cHHnVOehuSer-0hvgIh2XfSq6QeBb9bPxwHr85Ks2GttXRChmn2rSrbhasnbnIwMGSbffktVnLHDk1zD3qXCJ0DNaGdgg1S89gUOWYPol0wRGXmuYrEVpGHlO0TjmopcCCB7h1tNH4q3JTxk5lfNBbN5nE0CdjIJe_sr5O50ZT7686rRfEBDZUpvmqSvOOv18Nn9QTcG5PmPe6A6bWnFtKL7E4gdA7T0GG9c5o1Jp7rsFmMaCWEkxbaNKcfR3VucPuStq4lLENWA3-60sNyHKAPYhwT2s2w4s0m3cMiK7xkEidDptpy8L49IyJ1BmHxPpLlVF371X-o9dpRM5LYjXWjDC_v1QKOkkMAzQ3jcK3mRpUWKXBKO6Ts-Bupsdbm2Cl2fTFaXTjwRZT990d2FhXXoDI-gROqb30Whf3Z2ZtHptnDf1zk6WJO1E_VlX8yH3oOMMBZch51mL0NnffPC2Y"}, :body=>{:content=>"test-content", :impact=>7, :ease=>8, :confidence=>9}}}
{:verb=>:get, :path=>"/ideas", :options=>nil}
/Users/ursa/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:286:in `generate': only generation of JSON objects or arrays allowed (JSON::GeneratorError)
	from /Users/ursa/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:286:in `pretty_generate'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:47:in `block in build_message'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:31:in `map'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:31:in `build_message'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/review_quiz.rb:11:in `perform'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/lib/cm_quiz/cli.rb:19:in `test'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/gems/cm_quiz-0.0.3/bin/cm-quiz:8:in `<top (required)>'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/cm-quiz:23:in `load'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/cm-quiz:23:in `<main>'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ursa/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by ocowchun** [comment]
Hi @venantius I think `nil` is a valid argument for  `JSON.pretty_generate`, but I think we can still skip the `Request options` part when `options` is `nil`.

I just push a new version of `cm-quiz`. You can install the new version through execute following command

```sh
$ gem install cm_quiz
```

I guess the reason that `options`  being `nil` is because the test code failed before we declare `@options` in `cm_quiz/review/get_ideas.rb`. The most likely reason is that `Factory::User` or `Factory::Idea` is failed and then it directly terminates the test before declare the variable `@options`.

Hope these information can help you 🙂

**Comment by venantius** [comment]
Great, everything seems to be working now. Cheers!
