### ISSUE TITLE
Unexpected token # in JSON at position 0

### ISSUE THREAD

**Issue by nikolovlazar** [codementordev/cm-quiz#2]
It happens when I try to run the command:
`cm-quiz test --endpoint http://localhost:8080`
My API is not done yet, only the /ideas is still left to be implemented. But when I run the command it breaks on the route /me, but when I call that route from Postman it all works fine.
This is the error:
```
SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/Users/lazarnikolov/projects/private/cm-small-project/node_modules/body-parser/lib/types/json.js:157:10)
    at parse (/Users/lazarnikolov/projects/private/cm-small-project/node_modules/body-parser/lib/types/json.js:83:15)
    at /Users/lazarnikolov/projects/private/cm-small-project/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/Users/lazarnikolov/projects/private/cm-small-project/node_modules/raw-body/index.js:224:16)
    at done (/Users/lazarnikolov/projects/private/cm-small-project/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/lazarnikolov/projects/private/cm-small-project/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I'm not sure what's going on on Ruby's side because I have 0 experience with Ruby. I'm doing my project in NodeJS, and as we can see it breaks in the body-parser library. When I debug it on my end, I can see that sometimes I get the body parsed as "null" (actual string).

**Comment by nikolovlazar** [comment]
UPDATE! I've switched to [busboy](https://www.npmjs.com/package/express-busboy) and it's not breaking anymore. Might wanna see why it breaks for body-parser, or inform the people about the situation.

**Comment by foysalit** [comment]
This is still an issue with express body-parser package. At least let people know before they start the project/test?
